# typed: false
# frozen_string_literal: true

# Generated by scripts/render-formula.sh — do not edit by hand.
# Changes land via the next release of mitre/claude-statusline.
class ClaudeStatusline < Formula
  desc "Fast, configurable status line for Claude Code"
  homepage "https://github.com/mitre/claude-statusline"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mitre/claude-statusline/releases/download/v0.1.1/claude-statusline-0.1.1-darwin-arm64.tar.gz"
      sha256 "a91b07d3d2ec83742f2764a0e01ffef78be76aa1ac432396ad4c029feb928f90"
    else
      url "https://github.com/mitre/claude-statusline/releases/download/v0.1.1/claude-statusline-0.1.1-darwin-amd64.tar.gz"
      sha256 "3d3c798292bfb296a89fd3822bff0bfb902121233b8d3ffe15c9be52e36c85a1"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/mitre/claude-statusline/releases/download/v0.1.1/claude-statusline-0.1.1-linux-arm64.tar.gz"
      sha256 "5aa626f7232f770444721c8385b1dc8c9a2e0e75fbb71f9cddfb3586ec914dd7"
    else
      url "https://github.com/mitre/claude-statusline/releases/download/v0.1.1/claude-statusline-0.1.1-linux-amd64.tar.gz"
      sha256 "b042a09d0e6bdb1aa07d6a8d627bafe553a9ec09a12ab2f04e9ab2440943e207"
    end
  end

  def install
    bin.install "claude-statusline"
  end

  def caveats
    <<~EOS
      Point Claude Code at the binary in ~/.claude/settings.json:
        "statusLine": {"type": "command", "command": "#{opt_bin}/claude-statusline", "padding": 0}
      Or install via the Claude Code plugin and run /claude-statusline:setup.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/claude-statusline --version")
  end
end
