# typed: false
# frozen_string_literal: true

# Generated by scripts/render-formula.sh — do not edit by hand.
# Changes land via the next release of mitre/claude-statusline.
class ClaudeStatusline < Formula
  desc "Fast, configurable status line for Claude Code"
  homepage "https://github.com/mitre/claude-statusline"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mitre/claude-statusline/releases/download/v0.2.0/claude-statusline-0.2.0-darwin-arm64.tar.gz"
      sha256 "605a9d29670c9d73ed73629572ce07c816e929d2646335fa1ee6181b6bca3263"
    else
      url "https://github.com/mitre/claude-statusline/releases/download/v0.2.0/claude-statusline-0.2.0-darwin-amd64.tar.gz"
      sha256 "737246f1e4f2c9d84a6d876a2a94f4c685929df7c781831aa25ad62860ba2929"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/mitre/claude-statusline/releases/download/v0.2.0/claude-statusline-0.2.0-linux-arm64.tar.gz"
      sha256 "a406f43f8cb04b7577a14fb11db632708bc04a9701dbb43dc983435634840e10"
    else
      url "https://github.com/mitre/claude-statusline/releases/download/v0.2.0/claude-statusline-0.2.0-linux-amd64.tar.gz"
      sha256 "49961557f4565cd7aa3b6f506dd5ce99ebead1c70ca871e5bf2e0d80836e4de2"
    end
  end

  def install
    bin.install "claude-statusline"
  end

  def caveats
    <<~EOS
      Point Claude Code at the binary in ~/.claude/settings.json:
        "statusLine": {"type": "command", "command": "#{opt_bin}/claude-statusline", "padding": 0}
      Or install via the Claude Code plugin and run /claude-statusline:setup.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/claude-statusline --version")
  end
end
