# typed: false
# frozen_string_literal: true

# Generated by scripts/render-formula.sh — do not edit by hand.
# Changes land via the next release of mitre/claude-statusline.
class ClaudeStatusline < Formula
  desc "Fast, configurable status line for Claude Code"
  homepage "https://github.com/mitre/claude-statusline"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mitre/claude-statusline/releases/download/v0.3.0/claude-statusline-0.3.0-darwin-arm64.tar.gz"
      sha256 "00c3c63426ed36576f55400e8fe75985b86687c8f961cdbc9d3550ba2b713816"
    else
      url "https://github.com/mitre/claude-statusline/releases/download/v0.3.0/claude-statusline-0.3.0-darwin-amd64.tar.gz"
      sha256 "cc758949a0e2afaa467831914d73dbbaacd5160889b4d5592b47e69c035627fa"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/mitre/claude-statusline/releases/download/v0.3.0/claude-statusline-0.3.0-linux-arm64.tar.gz"
      sha256 "5e94a48962f8981ce19bcb98d2c469f4cf6f31bbbbcfd6d9e354f35d1d0d0fe7"
    else
      url "https://github.com/mitre/claude-statusline/releases/download/v0.3.0/claude-statusline-0.3.0-linux-amd64.tar.gz"
      sha256 "714872cf218f61f4e7c7f89f9f637b85d32cdd85f4affb367ded3c3ab7d64408"
    end
  end

  def install
    bin.install "claude-statusline"
  end

  def caveats
    <<~EOS
      Point Claude Code at the binary in ~/.claude/settings.json:
        "statusLine": {"type": "command", "command": "#{opt_bin}/claude-statusline", "padding": 0}
      Or install via the Claude Code plugin and run /claude-statusline:setup.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/claude-statusline --version")
  end
end
